// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeVCToyFeature } from "./FeVCToyFeature";

export interface FeFeatureParamMap { features: Array<FeVCToyFeature>, }