// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeFeatureParamMap } from "./FeFeatureParamMap";

export interface FeVCToy { toy_id: number, toy_name: string, battery_level: number, toy_connected: boolean, param_feature_map: FeFeatureParamMap, listening: boolean, }