// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeScanEvent } from "./FeScanEvent";

export type FeCoreEvent = { kind: "Scan", data: FeScanEvent };