// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FeLevelTweaks { minimum_level: number, maximum_level: number, idle_level: number, smooth_rate: number, }