// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeLevelTweaks = { minimum_level: number, maximum_level: number, idle_level: number, smooth_rate: number, linear_position_speed: number, rate_tune: number, constant_level: number, };
