// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeProcessingMode } from "./FeProcessingMode";
import type { PenetrationSystemType } from "./PenetrationSystemType";

export type FePenetrationSystem = { pen_system_type: PenetrationSystemType, pen_system_processing_mode: FeProcessingMode, };
