// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeVCToy } from "./FeVCToy";

export type FeToyEvent = { "kind": "Add", "data": FeVCToy } | { "kind": "Remove", "data": number } | { "kind": "Update", "data": FeVCToy };
