// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeVCToy } from "./FeVCToy";

export interface FeToyAddEvent { kind: string, toy: FeVCToy, }