// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeProcessingMode } from "./FeProcessingMode";

export type FeToyParameter = { parameter: string, processing_mode: FeProcessingMode, };
