// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeVCToy } from "./FeVCToy";

export type FeToyEvent = { FeToyAdd: FeVCToy } | { FeToyRemove: number };