// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeVCToyAnatomy } from "./FeVCToyAnatomy";
import type { FeVCToyFeature } from "./FeVCToyFeature";

export type FeToyAlter = { Feature: FeVCToyFeature } | { OSCData: boolean } | { Anatomy: FeVCToyAnatomy };