// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeVCToyAnatomy } from "./FeVCToyAnatomy";
import type { FeVCToyFeature } from "./FeVCToyFeature";

export interface FeVCToy { toy_id: number | null, toy_name: string, toy_anatomy: FeVCToyAnatomy, battery_level: number | null, toy_connected: boolean, features: Array<FeVCToyFeature>, listening: boolean, osc_data: boolean, sub_id: number, }