// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeVCToyAnatomy = "Anus" | "Breasts" | "Buttocks" | "Chest" | "Clitoris" | "Face" | "Feet" | "FootL" | "FootR" | "HandLeft" | "HandRight" | "Hands" | "Labia" | "Mouth" | "NA" | "Nipples" | "Penis" | "Perineum" | "Testicles" | "Vagina" | "Vulva" | "Wrist";