// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeLevelTweaks } from "./FeLevelTweaks";
import type { FeVCFeatureType } from "./FeVCFeatureType";

export interface FeVCToyFeature { feature_enabled: boolean, feature_type: FeVCFeatureType, osc_parameter: string, feature_index: number, feature_levels: FeLevelTweaks, smooth_enabled: boolean, }