// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeLevelTweaks } from "./FeLevelTweaks";
import type { FePenetrationSystem } from "./FePenetrationSystem";
import type { FeToyParameter } from "./FeToyParameter";
import type { FeVCFeatureType } from "./FeVCFeatureType";

export interface FeVCToyFeature { feature_enabled: boolean, feature_type: FeVCFeatureType, osc_parameters: Record<string, FeToyParameter>, penetration_system: FePenetrationSystem, feature_index: number, flip_input_float: boolean, feature_levels: FeLevelTweaks, smooth_enabled: boolean, rate_enabled: boolean, }