// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeOSCNetworking } from "./FeOSCNetworking";

export interface FeVibeCheckConfig { networking: FeOSCNetworking, scan_on_disconnect: boolean, }