name: lint

on:
  push:
    branches:
      - gh-actions
  pull_request:
    branches:
      - main

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: yarn
      - name: install deps via yarn
        run: yarn
      - name: run lint
        run: yarn lint
      - name: run format
        run: yarn format:check
